### ISSUE TITLE
No installed scripts run on this website

### ISSUE THREAD

**Issue by MichaelFanous2** [1v/dislike-truck#1]
Followed all instructions on read me and nothing happened i checked tampermonkey and it says no scrripts run on this website

**Comment by 1v** [comment]
It's only for Firefox and Greasemonkey.

**Comment by MichaelFanous2** [comment]
yes that is what is says on firefox

**Comment by 1v** [comment]
With greasemonkey? Did you activate script:
![](http://img-fotki.yandex.ru/get/233740/203537249.16/0_17568e_fa47e9c8_orig.png)
I've just checked and it's working with latest version of script.
