### ISSUE TITLE
I always get this

### ISSUE THREAD

**Issue by elsillygato** [1v/dislike-truck#10]
https://accounts.google.com/signin/oauth/error?authError=ChVyZWRpcmVjdF91cmlfbWlzbWF0Y2gSywJUaGUgSmF2YVNjcmlwdCBvcmlnaW4gaW4gdGhlIHJlcXVlc3QsIGh0dHBzOi8vd3d3LnlvdXR1YmUuY29tLCBkb2VzIG5vdCBtYXRjaCB0aGUgb25lcyBhdXRob3JpemVkIGZvciB0aGUgT0F1dGggY2xpZW50LiBWaXNpdCBodHRwczovL2NvbnNvbGUuZGV2ZWxvcGVycy5nb29nbGUuY29tL2FwaXMvY3JlZGVudGlhbHMvb2F1dGhjbGllbnQvNTY5MTIzODExNDcwLTlhN2ExZDNtMmlyMnNiOW1zZm9zZjE1aTI4bHNtdWV2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tP3Byb2plY3Q9NTY5MTIzODExNDcwIHRvIHVwZGF0ZSB0aGUgYXV0aG9yaXplZCBKYXZhU2NyaXB0IG9yaWdpbnMuGkVodHRwOi8vZGV2ZWxvcGVycy5nb29nbGUuY29tL2FjY291bnRzL2RvY3MvT0F1dGgyTG9naW4jc2V0cmVkaXJlY3R1cmkgkAM%3D&client_id=569123811470-9a7a1d3m2ir2sb9msfosf15i28lsmuev.apps.googleusercontent.com

**Comment by 1v** [comment]
Try this settings.
![image](https://user-images.githubusercontent.com/6566370/82943515-6f5b6380-9fa2-11ea-8c28-17c0eeb6d2fd.png)
![image](https://user-images.githubusercontent.com/6566370/82943693-b21d3b80-9fa2-11ea-9ba2-f6d07a8d5d8a.png)

**Comment by elsillygato** [comment]
Thank you!

Btw, what is the gif that plays when you click dislike for?
Also, how can you control how many dislikes the video get?

**Comment by 1v** [comment]
> Btw, what is the gif that plays when you click dislike for?

It's Sergey Simonov, people dislike his videos for years.

> Also, how can you control how many dislikes the video get?

Each video on channel is disliked once by your account. If you choose another account - each video will be disliked again.
