### ISSUE TITLE
Google Oauth2 ERROR

### ISSUE THREAD

**Issue by jinxx0** [1v/dislike-truck#11]
We detected a problem with the Product name shown to users field. Make sure it describes your specific product and avoid using a name that suggests that your product comes from Google or another company. Learn more
how i can fix tihs

**Comment by 1v** [comment]
Where do you get this error?

**Comment by jinxx0** [comment]
On creating oauth2

**Comment by jinxx0** [comment]
![2](https://user-images.githubusercontent.com/43272857/84373345-1d8f1c00-abe5-11ea-9384-43b578da725e.PNG)
