### ISSUE TITLE
Not Working :(

### ISSUE THREAD

**Issue by saumickm** [1v/dislike-truck#14]
I made an API key and OAuth Client and added to the script but it still didn't work, is there anyother way I can make this work?

**Comment by 1v** [comment]
It is working if configured correctly. I'm planning to do guide but I don't know if it worth because youtube api only allow 200 dislikes per day.

**Comment by foxietbh** [comment]
i have put the api key and client in the script inside tampermonkey but the interface still doesnt appear when i open youtube

**Comment by 1v** [comment]
It only shows on channel page.

**Comment by foxietbh** [comment]
ok now it shows, but do i have to register to dislike? because when registing it says "Error 400: redirect_uri_mismatch
The JavaScript origin in the request, https://www.youtube.com, does not match the ones authorized for the OAuth client."

**Comment by 1v** [comment]
It means your settings is wrong. Try this:
![image](https://user-images.githubusercontent.com/6566370/89941465-bbbe5300-dc23-11ea-9dfe-60635237f47c.png)

**Comment by Karpuz153** [comment]
Please make a guide video c:
