### ISSUE TITLE
am i meant to have to fill out all this for client id?

### ISSUE THREAD

**Issue by August2211** [1v/dislike-truck#15]
^^

**Comment by August2211** [comment]
![Uploading Screenshot 2020-06-12 at 09.20.21.png…]()

**Comment by August2211** [comment]
![Screenshot 2020-06-12 at 09 20 21](https://user-images.githubusercontent.com/53059031/96689176-55bc1d80-1382-11eb-9848-6a664db018bf.png)

**Comment by August2211** [comment]
![Screenshot 2020-10-21 at 09 47 17](https://user-images.githubusercontent.com/53059031/96689263-72f0ec00-1382-11eb-9f1a-72fd3d3c5555.png)

**Comment by 1v** [comment]
On this page I added only in Authorized domains youtube.com.

**Comment by August2211** [comment]
even if it says it needs to be sent to verification?

**Comment by August2211** [comment]
![Screenshot 2020-10-22 at 09 41 22](https://user-images.githubusercontent.com/53059031/96840469-c890cb80-144a-11eb-8d6c-b27e1528b2b0.png)

**Comment by August2211** [comment]
and also what would i do for a name if i just submit it for verification?

**Comment by August2211** [comment]
Do you have discord or something where we can discuss?

**Comment by 1v** [comment]
You don't need submit for verification.

**Comment by August2211** [comment]
![Screenshot 2020-10-26 at 13 08 02](https://user-images.githubusercontent.com/53059031/97170648-58f14800-178c-11eb-9560-9a6db01fa26d.png)

**Comment by August2211** [comment]
after i register its still 0/0 and no videos get disliked

**Comment by August2211** [comment]
also gif dissaperes when i click dislike

**Comment by August2211** [comment]
fixed the client id btw

**Comment by 1v** [comment]
Script was broken. Just fixed.

**Comment by August2211** [comment]
still not doing anything and both gif and register button is gone

**Comment by 1v** [comment]
Do you get alert?

**Comment by August2211** [comment]
where? not on youtube, haven't checked google api if thats what you mean

**Comment by August2211** [comment]
or do you mean on tampermonkey?

**Comment by 1v** [comment]
On browser. Do you logged in to your account?

**Comment by August2211** [comment]
Yes on one of them

**Comment by 1v** [comment]
Then logout and login. If it not works then must be your api key settings is wrong.

**Comment by August2211** [comment]
is gif and register button meant to be gone?

**Comment by August2211** [comment]
![Screenshot 2020-10-27 at 09 20 43](https://user-images.githubusercontent.com/53059031/97275050-bee5da00-1835-11eb-8532-2a7be696b2ec.png)

**Comment by August2211** [comment]
i noticed it says scope in your code am i meant to add a scope on google api?

**Comment by 1v** [comment]
Yep you need YouTube Data API v3 to be enabled at dashboard.

**Comment by August2211** [comment]
it works :D

**Comment by August2211** [comment]
thank

**Comment by August2211** [comment]
does it work with multiple accounts?

**Comment by 1v** [comment]
Yes, there should be window if you have multiple accounts. But if you've already choose account then you need to delete cookies. Previously it was possible to force account choose through Register button, but they screwed something and it didn't work currently.
