### ISSUE TITLE
Totally lost

### ISSUE THREAD

**Issue by ghost** [1v/dislike-truck#16]
I have made and deleted about 5 projects trying to get this app to work. You make it sound so easy to get an API and Client ID but when I do and put them in I either get the Dislike Bar with 0/0 or nothing at all. I followed the instructions in the last Issue Request that is still up like enabling YouTube API v3 but even then the instructions aren't crystal clear. Can you please make a step by step guide with pictures on how to properly get your API and Client ID for this app? Because honestly it's not worth the frustration of fumbling about.

**Comment by 1v** [comment]
Added tutorial https://github.com/1v/dislike-truck/wiki

**Comment by BeScarred** [comment]
does this affect one video or everything in my feed?

**Comment by ghost** [comment]
This allows you to go to a channel, click a dislike button that pops up next to the subscribe button, and it'll dislike every video by that person, it does not interact with your feed.
