### ISSUE TITLE
Newbie - Got two red boxes up in toolbar on tampermonkey

### ISSUE THREAD

**Issue by jesamms** [1v/dislike-truck#19]
I followed all the instruction but for some reason I am stumped.  I never get past the the red box with number 2 which I assume is for issues up in the tamper monkey icon in toolbar.  I would love to try this out.  
Thanks! 

![twored](https://user-images.githubusercontent.com/65485382/99610214-6393ab80-29df-11eb-8add-85a4cb429d39.jpg)
![Enabled](https://user-images.githubusercontent.com/65485382/99610240-727a5e00-29df-11eb-8cbf-49475f3e4cff.jpg)
![codejs](https://user-images.githubusercontent.com/65485382/99610262-7a3a0280-29df-11eb-88b0-8923cd32943f.jpg)

**Comment by 1v** [comment]
Reinstall script.
