### ISSUE TITLE
[question] Can you mass dislike comments with this?

### ISSUE THREAD

**Issue by JohnSmith2007** [1v/dislike-truck#25]
Can you mass dislike comments with this?

**Comment by 1v** [comment]
No

**Comment by pcroland** [comment]
And it wouldn't even make sense. Only you can see your dislikes, and it doesn't effect the like count. YouTube should remove the button.

**Comment by JohnSmith2007** [comment]
> YouTube should remove the button.

Are you brain dead?!! Do you want YouTube to become like Twitter, where you can't dislike anything?!
