### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by cecropiadeath** [1v/dislike-truck#26]
When I put in the YouTube url it says eslint parsing error unexpected token. What do I do?

**Comment by cecropiadeath** [comment]
And how many dislikes does it give out to one video?

**Comment by cecropiadeath** [comment]
?

**Comment by 1v** [comment]
Do you check README?

**Comment by cecropiadeath** [comment]
Yes, though I'd like a more clear answer to my questions

**Comment by 1v** [comment]
There is nowhere you can put youtube url.
