### ISSUE TITLE
Google says it is dangerous and blocked it

### ISSUE THREAD

**Issue by oofmcoofington** [1v/dislike-truck#28]
This might be just me but when I tried to use this and sign in, it gave me this "error"
![image](https://user-images.githubusercontent.com/79936862/109701192-bc3b1e80-7b60-11eb-8f7d-5c3dd4f30e55.png)

**Comment by oofmcoofington** [comment]
This is for the second sign in

**Comment by 1v** [comment]
There is link at bottom.

**Comment by oofmcoofington** [comment]
I don't see a link. Im sorry if it is obvious but this is what it shows. It is the full window also 
![image](https://user-images.githubusercontent.com/79936862/109854375-f79f2100-7c24-11eb-998c-f35ca33a5560.png)

**Comment by 1v** [comment]
Did you follow guide?

**Comment by oofmcoofington** [comment]
Yeah I did everything. It shows the bar and Dislike button, but when I go to sign in, it shows that
