### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Codingo1** [1v/dislike-truck#32]
Script not working unfortunately. Firefox Console says (API and key replaced by xxx):

XHRPOSThttps://content-youtube.googleapis.com/youtube/v3/videos/rate?rating=dislike&id=_xxxxxxxx_&key=_xxxxxxxxxxxxxxxxxxxx_
[HTTP/2 401 Unauthorized 134ms]

	
POST
	https://content-youtube.googleapis.com/youtube/v3/videos/rate?rating=dislike&id=_xxxxxxxx_&key=_xxxxxxxxxxxxxxxxxxxx_
Status401
Unauthorized
VersionHTTP/2
Übertragen897 B (509 B Größe)
Referrer Policyno-referrer-when-downgrade

    	

JSON:

{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Login Required.",
        "domain": "global",
        "reason": "required",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}

**Comment by 1v** [comment]
Nope. There is problem with your project settings. I think I had same error but I don't remember what I changed to fix it.

**Comment by Codingo1** [comment]
well, i did everything that's stated in the guide...

then i think first it gave me 403 and in the JSON it said i should allow usage of youtube data api v3. i activated it in the cloud platform and it worked appearently. that was not part of the guide anymore already. probably a new step because youtube updated something meanwhile? anyway, now i'm stuck at 401. any hint you can give me? YouTube Data API v3 is correct, right?

**Comment by 1v** [comment]
Create another project or try with same project but another browser.

**Comment by Codingo1** [comment]
new project created, same error.

is it normal that tampermonkey displays all these warnings and errors?
[https://cdn1.bbcode0.com/uploads/2021/3/17/257316e23e854b8a8abf232d5918ef64-full.png](https://cdn1.bbcode0.com/uploads/2021/3/17/257316e23e854b8a8abf232d5918ef64-full.png)

**Comment by 1v** [comment]
I created new project and script worked. Only thing was missing in guide is publishing app.
