### ISSUE TITLE
Script still not working

### ISSUE THREAD

**Issue by kyle172** [1v/dislike-truck#5]
Is this not cross compatible with other platforms? I'm not using windows and the script still seems to be not working unless Google has patched it quickly

**Comment by 1v** [comment]
I've checked at Ubuntu and it's working. But sometimes buttons is not loading, try CTRL+F5.

**Comment by Mikeymyers** [comment]
U think it works for debian

**Comment by Mikeymyers** [comment]
I got it to work but after it says 223/223 what does that mean lol I never got to click on what did to do it on

**Comment by 1v** [comment]
It's total number of videos and how much currently disliked.

**Comment by ghost** [comment]
I'm using windows and did everything like says in the instruction, but button "Dislike" doesn't still appears, even after reloading or pressing CTRL+F5.

**Comment by 1v** [comment]
It's working for me and I see activity on API key, so it also working for other people.

**Comment by 1v** [comment]
Check if this urls accessible for you:
```
https://code.jquery.com/jquery-1.11.3.min.js
https://apis.google.com/js/client.js?v=1
https://raw.githubusercontent.com/kimmobrunfeldt/progressbar.js/2af42a3a48979a72a93b989a00bf3e8e75f9f22d/dist/progressbar.js
```
Might be problem with loading scripts.

**Comment by WobbyChip** [comment]
I checked all these links and I am able to access them, but this
script still doesn't work for me, because the button "Dislike" or
"Register" doesn't display in YouTube.

**Comment by cadogan207** [comment]
Just tried it out in Windows 8.1 (Chrome and Opera) and it never pops up. Disabled all my extensions and the script is running. Maybe it needs an older version of Chrome? Tried to check all the js scripts and they load up. Is it till working for you? How is yours setup?

**Comment by WobbyChip** [comment]
Now, after I removed every my extension it works normally, interesting who of extensions is blocking it.

**Comment by kyle172** [comment]
Tried on FireFox 62 64 bit on Apple computer also browser extension came up once in the toolbar once but it kept saying after that no scripts found even  when it was enabled

**Comment by 1v** [comment]
@kyle172 I checked at macos latest chrome and it's working.

**Comment by Autotren** [comment]
Could please someone explain how do I set it up, because for me, it loads the video normally!
I've tried on chrome and Firefox in osx.

**Comment by 1v** [comment]
@Autotren it loads on channel page beside subscribe button.

**Comment by Insigniaa** [comment]
I can't get this to work. I even can't see the login thing you describe. Using Chrome.

**Comment by OutBoundMan** [comment]
Is this meant to dislike every video on the channel once? Or will it mass dislike one video?

**Comment by 1v** [comment]
@OutBoundMan to dislike all videos within one channel.

**Comment by 1v** [comment]
Possible.

**Comment by OutBoundMan** [comment]
How much would you charge? I only need like and dislike, accounts, and proxies. Don't need comments or anything else.

**Comment by 1v** [comment]
@OutBoundMan sorry, I don't have time for this.

**Comment by ghost** [comment]
script is running but there is no dislike register buttons, must i exclude youtube.com ?

**Comment by 1v** [comment]
@sandman4812av for me buttons is there.

**Comment by domostry1432** [comment]
The script does not work. When the script ends dislike movies they have the same dislike number, they just look like they're dislike, just when you're done log out and watch the movie you've done dislike. Didnt add anything.

**Comment by 1v** [comment]
@domostry1432 when you open any video from channel do you see that dislike button is pressed?

**Comment by domostry1432** [comment]
@1v Yes, exactly i use 5 accounts to try it, vodeos looks like i dislike but dislike didnt go up.
(I click register and give rights for script before start dislike)

**Comment by 1v** [comment]
@domostry1432 I've tried with both youtube account and google account and videos got perfectly disliked and dislike counter is increased.

**Comment by Serdx** [comment]
Hello. I cant do anything. I DONT know how to use this program. I dont see neither a button of dislike of register. I just see all normal. No plus windows no anything.

**Comment by 1v** [comment]
@Serdx Working for me:
![](https://telegra.ph/file/9d8238df154b73bccf766.png)

**Comment by Serdx** [comment]
@1v Okay I jus checked and it was because of some of my extensions and my dark theme. Thank you.
It would be better if I can select a video to dislike..

**Comment by Serdx** [comment]
@1v Could you make this but only for one video? I mean, this dislikes all the videos but I only want one of them.

**Comment by 1v** [comment]
@Serdx just press dislike button manually 😄 .

**Comment by ghost** [comment]
Google wont allow me to sign in

**Comment by 1v** [comment]
@omshabazz you're right. They added limit for user authentications, so I requested increase.
