### ISSUE TITLE
google took down

### ISSUE THREAD

**Issue by Luckkz** [1v/dislike-truck#8]
Hi im trying to use your script but google blocked the app
![oof](https://user-images.githubusercontent.com/60667751/73774204-7bb17b80-477b-11ea-958c-ce822be6e402.PNG)

**Comment by 1v** [comment]
I know about this. Sent request for verification and no answer yet.

**Comment by 1v** [comment]
They provided giant form to fill in that I can't fill. So project currently suspended.
You can create your own API key and client id and add it here https://github.com/1v/dislike-truck/blob/7943b93e7562f78d030f66e90510b37c726450e1/dislike-truck.user.js#L22-L23.

**Comment by koloved** [comment]
Thank you for the script, but sorry where can i create my own API key ?

**Comment by 1v** [comment]
Here https://console.cloud.google.com/apis/dashboard

**Comment by 5l1v3r1** [comment]
i created my own api key but the buttons not showing on youtube pages.

**Comment by 1v** [comment]
Buttons will show anyways. API key required for script to work. Btw just created key myself and script is working.

**Comment by 1v** [comment]
Disliked like 200 videos and limit is reached :laughing:. So youtube api currently basically useless.

**Comment by epic-developer** [comment]
wait where on api dashboard
